module "vpc" {
  source              = "../elb/"
  vpc_cidr            = "172.31.0.0/16"
  Subnet              = "subnetid"
  Secgroup            = "secgroup"
  Instanceport        = "insport"
  Instanceprotocol    = "insprotocol"
  Lbport              = "lbport"
  Lbprotocol          = "lbprotocol"
  healthcheckprotocol = "hcprotocol"
  healthcheckpath     = "hcpath"
  Instanceid          = "instanceid" 
  Name                = "name"
  Farm                = "farm"
 }
